#!/usr/bin/env python3
"""Run this before compiling C++ to regenerate shaders_embedded.hpp"""
import os

SHADER_DIR = "shaders"
OUT_FILE = "native/shaders_embedded.hpp"

SHADERS = {
    "SHADER_TEXTEST_VERT": "Textest.vert",
    "SHADER_TEXTEST_FRAG": "Textest.frag",
    "SHADER_MTOON_VERT":   "mtoon.vert",
    "SHADER_MTOON_FRAG":   "mtoon.frag",
    "SHADER_DEBUG_VERT":   "debug.vert",
    "SHADER_DEBUG_FRAG":   "debug.frag",
    "SHADER_WS1_VERT":    "WS1.vert",
    "SHADER_WS1_FRAG":    "WS1.frag",
}

lines = ["#pragma once", "#include <string>", ""]
lines.append(f"// This file is auto-generated by embed_shaders.py. Do not edit directly. For changes, edit the shader files in {SHADER_DIR}/ and run this {__file__} again.")
for var, filename in SHADERS.items():
    path = os.path.join(SHADER_DIR, filename)
    with open(path, "r") as f:
        src = f.read()
    lines.append(f"//── {filename.upper().replace('.', ' ')} ─────────────────────────────────────────────────")
    lines.append(f"// Source: {path} \n")
    lines.append(f"static const std::string {var} = R\"GLSL(")
    lines.append(src)
    lines.append(")GLSL\";")
    lines.append("")

with open(OUT_FILE, "w") as f:
    f.write("\n".join(lines))

print(f"✅ Generated {OUT_FILE}")