#pragma once
#include <string>

// This file is auto-generated by embed_shaders.py. Do not edit directly. For changes, edit the shader files in shaders/ and run this /home/tori/Codestuff/GrekoGameEngine/embed_shaders.py again.
//── TEXTEST VERT ─────────────────────────────────────────────────
// Source: shaders/Textest.vert 

static const std::string SHADER_TEXTEST_VERT = R"GLSL(
#version 430 core

// ==========================
// Vertex Attributes
// ==========================
layout (location = 0) in vec3 aPos;
layout (location = 1) in vec3 aNormal;
layout (location = 2) in vec2 aUV;
layout (location = 3) in ivec4 aJoints;
layout (location = 4) in vec4 aWeights;


layout (location = 5) in vec3 aMorph0; // Blink
layout (location = 6) in vec3 aMorph1; // Breath/Surprise
layout (location = 7) in vec3 aMorph2; // Mouth Phenomes
layout (location = 8) in vec3 aMorph3; // Buffer

// ==========================
// Uniforms
// ==========================
uniform mat4 model;
uniform mat4 view;
uniform mat4 projection;
uniform mat4 uJointMatrices[200];

uniform vec4 uMorphWeights; // [w0, w1, w2, w3]

// ==========================
// Outputs
// ==========================
out vec2 vUV;
out vec3 vNormal; // for lighting

void main()
{
    vec3 m0 = aMorph0 * uMorphWeights.x;
    vec3 m1 = aMorph1 * uMorphWeights.y;
    vec3 m2 = aMorph2 * uMorphWeights.z;
    vec3 m3 = aMorph3 * uMorphWeights.w;

    vec3 totalMorphOffset = m0 + m1 + m2 + m3;

    float totalWeight = aWeights.x + aWeights.y + aWeights.z + aWeights.w;

    vec3 morphedPos = aPos + totalMorphOffset;
    mat4 skinMatrix;
    if (totalWeight < 0.01) {
        // If no weights exist, fall back to a standard static pose
        skinMatrix = mat4(1.0);
    } else {
        skinMatrix = 
            aWeights.x * uJointMatrices[aJoints.x] +
            aWeights.y * uJointMatrices[aJoints.y] +
            aWeights.z * uJointMatrices[aJoints.z] +
            aWeights.w * uJointMatrices[aJoints.w];
    }

    // FLAG: The "Forehead Eye" Fix
    // OpenGL starts (0,0) at the bottom-left. 
    // VRM/glTF textures are authored for top-left.
    // Flipping the Y axis puts the eyes in the sockets.
    vec4 skinnedPos = skinMatrix * vec4(morphedPos, 1.0);
    vUV = vec2(aUV.x, 1.0 - aUV.y); 

    // Pass normal to fragment shader (adjust by model rotation)
    vNormal = mat3(transpose(inverse(model * skinMatrix))) * aNormal;

    gl_Position = projection * view * model * skinnedPos;
}
)GLSL";

//── TEXTEST FRAG ─────────────────────────────────────────────────
// Source: shaders/Textest.frag 

static const std::string SHADER_TEXTEST_FRAG = R"GLSL(
#version 430 core

in vec2 vUV;
out vec4 FragColor;

uniform sampler2D uMainTex;
uniform vec4 uBaseColorFactor;

void main()
{
    vec4 texColor = texture(uMainTex, vUV);

    // FLAG: Alpha Testing
    // This removes the "square" around eyelashes and the "fog" in the eyes.
    if (texColor.a < 0.05) {
        discard; 
    }

    // FLAG: Color Mixing
    // VRM models use uBaseColorFactor to tint the mesh (like making skin warmer).
    // If you only use 'texColor', you might lose some of the artist's intended look.
    vec4 color = texColor * uBaseColorFactor;

    // Output the final color
    FragColor = color;
}
)GLSL";

//── MTOON VERT ─────────────────────────────────────────────────
// Source: shaders/mtoon.vert 

static const std::string SHADER_MTOON_VERT = R"GLSL(
#version 130 core    //or 330

// FLAG: Standard Attributes (Passed from C++/Python)
layout (location = 0) in vec3 in_Vertex;
layout (location = 1) in vec3 in_Normal;
layout (location = 2) in vec2 in_UV;
layout (location = 3) in vec4 in_Joints;  // Which bones affect this vertex
layout (location = 4) in vec4 in_Weights; // How much each bone pulls

// FLAG: Uniforms (The "Muscle" data)
uniform mat4 u_ViewProjection;   // Camera Camera Camera
uniform mat4 u_Model;            // World Position of the Entity
uniform mat4 u_JointMatrices[128]; // The Skeleton (Max 128 bones)

// FLAG: Data for the MToon Fragment Shader
out vec2 uv;
out vec3 v_normal;
out vec3 v_worldPos;

void main() {
    // FLAG: The Skinning Calculation
    // This is the line that fixes the "explosion." 
    // We blend the matrices of the 4 joints based on their weights.
    mat4 skinMat = 
        in_Weights.x * u_JointMatrices[int(in_Joints.x)] +
        in_Weights.y * u_JointMatrices[int(in_Joints.y)] +
        in_Weights.z * u_JointMatrices[int(in_Joints.z)] +
        in_Weights.w * u_JointMatrices[int(in_Joints.w)];

    // Transform position into world space using the skin
    vec4 worldPos = u_Model * skinMat * vec4(in_Vertex, 1.0);
    
    // Final position on screen
    gl_Position = u_ViewProjection * worldPos;

    // Data for MToon lighting
    uv = in_UV;
    v_worldPos = worldPos.xyz;
    
    // Normal must be transformed by the same skinning matrix to stay aligned
    v_normal = normalize(mat3(u_Model * skinMat) * in_Normal);
}
)GLSL";

//── MTOON FRAG ─────────────────────────────────────────────────
// Source: shaders/mtoon.frag 

static const std::string SHADER_MTOON_FRAG = R"GLSL(
#version 130 // or use 330

uniform sampler2D p3d_Texture0;
uniform struct {
    vec4 color;
    vec4 position;
} p3d_LightSource[1];

uniform vec4 ambient;
in vec2 uv;
in vec3 v_normal;

void main() {
    vec4 tex = texture2D(p3d_Texture0, uv);
    
    // FLAG: Gamma Correction (Linear Space)
    // This is the #1 reason faces look "White ASF". 
    // It converts the texture to math-friendly values.
    vec3 linear_tex = pow(tex.rgb, vec3(2.2));

    // FLAG: Genshin Shadow Tint
    // Instead of black, shadows on skin should be a mix of Orange and Pink.
    // vec3(Red, Green, Blue) -> 1.0, 0.7, 0.6 is a warm peach.
    vec3 shadow_tint = vec3(1.0, 0.7, 0.6); 

    vec3 light_dir = normalize(p3d_LightSource[0].position.xyz);
    
    // FLAG: Shadow Wrap (-0.3)
    // Pushing this negative forces the shadow to wrap around her cheeks.
    float dot_prod = dot(v_normal, light_dir) - 0.3;
    float intensity = smoothstep(0.0, 0.05, dot_prod);
    
    // FLAG: The Multi-Tone Mix
    // We mix the texture with our warm shadow tint for the dark side.
    vec3 shadow_side = linear_tex * shadow_tint * 0.5; 
    vec3 lit_side = linear_tex;
    
    vec3 linear_ambient = pow(ambient.rgb, vec3(2.2));

    vec3 lit_rgb = mix(shadow_side, lit_side, intensity);
    vec3 final_rgb = lit_rgb + (linear_tex * linear_ambient);
    
    // FLAG: Global Brightness Cap (0.7)
    // This prevents your GT 710 from blowing out the white pixels.
    final_rgb *= p3d_LightSource[0].color.rgb * 0.7;
    
    // Convert back to Gamma Space for the monitor
    gl_FragColor = vec4(pow(final_rgb, vec3(1.0/2.2)), tex.a);
}
)GLSL";

//── DEBUG VERT ─────────────────────────────────────────────────
// Source: shaders/debug.vert 

static const std::string SHADER_DEBUG_VERT = R"GLSL(
#version 330 core
layout (location = 0) in vec3 aPos;

uniform mat4 model;
uniform mat4 view;
uniform mat4 projection;

void main() {
    // FLAG: The Standard 3D Formula
    // Multiply from right to left: Proj * View * Model * Position
    gl_Position = projection * view * model * vec4(aPos, 1.0);
}

)GLSL";

//── DEBUG FRAG ─────────────────────────────────────────────────
// Source: shaders/debug.frag 

static const std::string SHADER_DEBUG_FRAG = R"GLSL(
#version 330 core
in vec2 TexCoords;
out vec4 FragColor;

void main() {
    // If we see this neon pink, we know the shader is working
    FragColor = vec4(1.0, 0.0, 1.0, 1.0); 
}
)GLSL";

//── WS1 VERT ─────────────────────────────────────────────────
// Source: shaders/WS1.vert 

static const std::string SHADER_WS1_VERT = R"GLSL(
#version 430 core

// ==========================
// Vertex Attributes
// ==========================
layout (location = 0) in vec3 aPos;
layout (location = 1) in vec3 aNormal;
layout (location = 2) in vec2 aUV;
layout (location = 3) in ivec4 aJoints;
layout (location = 4) in vec4 aWeights;

layout (location = 5) in vec3 aMorph0; // Blink
layout (location = 6) in vec3 aMorph1; // Breath/Surprise
layout (location = 7) in vec3 aMorph2; // Mouth Phenomes
layout (location = 8) in vec3 aMorph3; // Buffer

// ==========================
// Uniforms
// ==========================
uniform mat4 model;
uniform mat4 view;
uniform mat4 projection;
uniform mat4 uJointMatrices[1000]; // Array of joint transformation matrices
//layout(std430, binding = 0)
//buffer JointBuffer
//{
//    mat4 uJointMatrices[];
//};

uniform vec4 uMorphWeights; // [w0, w1, w2, w3]

// ==========================
// Outputs
// ==========================
out vec2 vUV;
//out vec3 vNormal; // for lighting
out vec3 vWorldNormal; // World-space normal  — for NdotL, fresnel
out vec3 vWorldPos;    // World-space position — for view direction

void main()
{
    vec3 m0 = aMorph0 * uMorphWeights.x;
    vec3 m1 = aMorph1 * uMorphWeights.y;
    vec3 m2 = aMorph2 * uMorphWeights.z;
    vec3 m3 = aMorph3 * uMorphWeights.w;

    vec3 totalMorphOffset = m0 + m1 + m2 + m3;

    float totalWeight = aWeights.x + aWeights.y + aWeights.z + aWeights.w;

    vec3 morphedPos = aPos + totalMorphOffset;
    mat4 skinMatrix;
    if (totalWeight < 0.01) {
        // If no weights exist, fall back to a standard static pose
        skinMatrix = mat4(1.0);
    } else {
        skinMatrix = 
            aWeights.x * uJointMatrices[aJoints.x] +
            aWeights.y * uJointMatrices[aJoints.y] +
            aWeights.z * uJointMatrices[aJoints.z] +
            aWeights.w * uJointMatrices[aJoints.w];

        vec4 pos = vec4(aPos,1.0);
    }

    // FLAG: The "Forehead Eye" Fix
    // OpenGL starts (0,0) at the bottom-left. 
    // VRM/glTF textures are authored for top-left.
    // Flipping the Y axis puts the eyes in the sockets.
    vec4 skinnedPos = skinMatrix * vec4(morphedPos, 1.0);
    vUV = vec2(aUV.x, 1.0 - aUV.y); 

    // Pass normal to fragment shader (adjust by model rotation)
    mat3 normalMatrix = transpose(inverse(mat3(model * skinMatrix)));
    vWorldNormal = normalize(normalMatrix * aNormal);
    vWorldPos = vec3(model * skinnedPos);

    //mat3 normalMatrix = mat3(model * skinMatrix); 
    //vNormal = normalize(normalMatrix * aNormal);

    gl_Position = projection * view * model * skinnedPos;
}

)GLSL";

//── WS1 FRAG ─────────────────────────────────────────────────
// Source: shaders/WS1.frag 

static const std::string SHADER_WS1_FRAG = R"GLSL(
#version 430 core

// ==========================
// Inputs
// ==========================
in vec2 vUV;
in vec3 vWorldNormal;
in vec3 vWorldPos;

// ==========================
// Output
// ==========================
out vec4 FragColor;

// ==========================
// Textures (always active)
// ==========================
uniform sampler2D uMainTex;

// ==========================
// Material
// ==========================
uniform vec4 uBaseColorFactor;

// ==========================
// Lighting
// ==========================
uniform vec3 uLightDirection; // Direction FROM the light source (will be negated below)
uniform vec3 uLightColor;
uniform vec3 uAmbientColor;

// ==========================
// Camera
// ==========================
uniform vec3 uCameraPos;

// ==========================
// Cel shading controls
// ==========================
// The article: "the most important thing is the transition between light and shadow,
// in Genshin they don't do an extreme hardness so 0.1 should be enough"
uniform float uLightSmooth;   // Main shadow edge softness — recommended: 0.1
uniform vec3  uShadowColor;   // Shadow region tint  — e.g. vec3(1.0, 0.82, 0.78) warm
uniform vec3  uBaseColor;     // Lit region tint     — e.g. vec3(1.0, 1.0, 1.0)

// ==========================
// Outer shadow controls
// ==========================
// Article: "add an outer extra small shadow with a different color.
//  Do another NdotL but offset it a bit and make the transition harder"
uniform float uOuterShadowOffset; // How far to shift the band toward shadow — try 0.15-0.25
uniform float uOuterShadowSmooth; // Edge hardness — try 0.02-0.05 (crisp)
uniform vec3  uOuterShadowColor;  // Slightly darker/cooler than uShadowColor

// ==========================
// Rim / edge highlight
// ==========================
// Article: "white outline around character, like in most animes"
// NOTE: The article implements this as a post-process Sobel pass. This is a
// shader-side fresnel approximation — good enough until you add a screen-space
// outline pass. See the #define FEATURE_SOBEL_OUTLINE note below.
uniform vec3  uRimColor;     // Usually white or pale blue — e.g. vec3(0.9, 0.95, 1.0)
uniform float uRimPow;       // Fresnel falloff — try 2.0-4.0
uniform float uRimIntensity; // Overall brightness — try 0.3-0.8

// ============================================================
// OPTIONAL FEATURES — uncomment the #define to enable each.
// Each one requires extra uniforms / textures listed above it.
// ============================================================

// ------------------------------------------------------------
// FEATURE: FACE SHADOW (SDF texture-driven shadow for face mesh)
// Article: "a simple NdotL is not the best option for the face.
//  We can edit normals but there is a better option [SDF texture]."
// Requires:
//   uniform sampler2D uFaceShadowTex; // R=0-180°, G=180-360°
//   uniform vec3 uHeadForward;        // head bone forward (world space XZ)
//   uniform vec3 uHeadRight;          // head bone right   (world space XZ)
// Only bind & set uIsFace=1 on your face draw call.
// ------------------------------------------------------------
// #define FEATURE_FACE_SHADOW

// ------------------------------------------------------------
// FEATURE: ANISOTROPIC HAIR HIGHLIGHT
// Article: "hair shines only when it receives light,
//  remove the sides with fresnel for a better result"
// Requires:
//   uniform sampler2D uHairMask;       // R channel = highlight position baked in texture
//   uniform float uAnisoFresnelPow;    // try 3.0-6.0
//   uniform float uAnisoFresnelIntensity; // try 1.0-2.0
// Only bind & set uIsHair=1 on hair draw calls.
// ------------------------------------------------------------
// #define FEATURE_ANISO_HAIR

// ------------------------------------------------------------
// FEATURE: METALLIC (gradient matcap-style)
// Article: "blend between diffuse texture and matcap.
//  Use a gradient texture, UV = dot(normal, normalize(viewDir + lightDir))"
// Requires:
//   uniform sampler2D uMetallicGradient; // 1D gradient strip texture
//   uniform float uMetallicBlend;        // 0=none, 1=full — try 0.5-1.0
// Only set uIsMetallic=1 on metallic material draw calls.
// ------------------------------------------------------------
// #define FEATURE_METALLIC

// ------------------------------------------------------------
// FEATURE: POST-PROCESS SOBEL OUTLINE
// Article: "detect edges using depth + normal scene texture, combine both"
// This requires a separate full-screen pass reading your depth/normal buffers.
// See: vrm_outline.frag (separate shader) for that implementation.
// The rim highlight below is your placeholder until that pass is wired up.
// ------------------------------------------------------------
// #define FEATURE_SOBEL_OUTLINE  <- implemented in vrm_outline.frag, not here


// ============================================================
// Conditional uniform declarations for optional features
// ============================================================
#ifdef FEATURE_FACE_SHADOW
uniform sampler2D uFaceShadowTex;
uniform vec3 uHeadForward;
uniform vec3 uHeadRight;
#endif

#ifdef FEATURE_ANISO_HAIR
uniform sampler2D uHairMask;
uniform float uAnisoFresnelPow;
uniform float uAnisoFresnelIntensity;
#endif

#ifdef FEATURE_METALLIC
uniform sampler2D uMetallicGradient;
uniform float uMetallicBlend;
#endif


// ============================================================
// Gran Turismo tonemapper
// Article: "keeps color saturation and fixes burned areas — ideal for cartoon style"
// Curve: https://www.desmos.com/calculator/gslcdxvipg
// Chosen over Neutral (blown brights) and ACES (desaturates) from Unity URP.
// ============================================================
vec3 granTurismoTonemap(vec3 x) {
    // GT constants tuned for anime saturation retention
    const float P  = 1.0;   // max display brightness
    const float a  = 1.0;   // contrast
    const float m  = 0.22;  // linear section start
    const float l  = 0.4;   // linear section length
    const float c  = 1.33;  // black tightness
    const float b  = 0.0;   // black pedestal

    float l0 = ((P - m) * l) / a;
    float S0 = m + l0;
    float S1 = m + a * l0;
    float C2 = (a * P) / (P - S1);
    float CP = -C2 / P;

    vec3 w0 = 1.0 - smoothstep(vec3(0.0), vec3(m), x);
    vec3 w2 = step(vec3(S0), x);
    vec3 w1 = 1.0 - w0 - w2;

    vec3 T = m * pow(clamp(x / m, 0.0, 1.0), vec3(c)) + b;
    vec3 L = m + a * (x - m);
    vec3 S = P - (P - S1) * exp(CP * (x - S0));

    return clamp(T * w0 + L * w1 + S * w2, 0.0, 1.0);
}


void main()
{
    // ================================================================
    // BASE SETUP
    // ================================================================
    vec4 texColor = texture(uMainTex, vUV);

    // Alpha clip — keep your threshold
    if (texColor.a < 0.05)
        discard;

    // Gamma -> linear (keep your existing conversion)
    vec3 albedo = pow(texColor.rgb, vec3(2.2));
    albedo *= uBaseColorFactor.rgb;

    vec3 N = normalize(vWorldNormal);
    vec3 L = normalize(-uLightDirection); // negate: uniform is direction FROM light
    vec3 V = normalize(uCameraPos - vWorldPos);


    // ================================================================
    // STEP 1 — MAIN CEL LIGHTING
    // Article: NdotL -> smoothstep(0, lightSmooth, NdotL) -> lerp shadow/base
    //
    // Replaces your hard if/else toon bands with the Genshin approach:
    // a single soft threshold. uLightSmooth=0.1 gives the characteristic
    // Genshin "not too hard, not too soft" transition.
    // ================================================================
    float lDot    = dot(L, N);
    float lSmooth = smoothstep(0.0, uLightSmooth, lDot);

    // Article: "lerp to tint shadow and light for more color control"
    // uShadowColor tints shadow regions, uBaseColor tints lit regions.
    // Your warm shadow tint (1.0, 0.82, 0.78) goes into uShadowColor.
    vec3 celColor = mix(uShadowColor, uBaseColor, lSmooth) * albedo;


    // ================================================================
    // STEP 2 — OUTER SHADOW
    // Article: "extra small shadow with a different color — another NdotL
    //  but offset a bit and make the transition harder, tint with similar color"
    //
    // This creates the thin darker band that appears just at the shadow
    // boundary — very visible on Genshin character bodies.
    // ================================================================
    float outerDot    = lDot - uOuterShadowOffset;
    float outerSmooth = smoothstep(0.0, uOuterShadowSmooth, outerDot);
    celColor = mix(uOuterShadowColor * albedo, celColor, outerSmooth);


    // ================================================================
    // STEP 3 — FACE SHADOW (optional — #define FEATURE_FACE_SHADOW)
    // Article: "use forward/right of head bone + SDF texture to avoid
    //  NdotL artifacts on rounded face geometry"
    // ================================================================
#ifdef FEATURE_FACE_SHADOW
    {
        // Project light direction onto the horizontal plane of the head
        float dotF = dot(uHeadForward.xz, L.xz);  // are we lit from front?
        float dotR = dot(uHeadRight.xz,   L.xz);  // which side is the light on?

        // Remap dotR through acos to get a 0-1 value representing light angle
        float dotRAcos    = (acos(clamp(dotR, -1.0, 1.0)) / 3.14159) * 2.0;
        float dotRAcosDir = (dotR < 0.0) ? (1.0 - dotRAcos) : (dotRAcos - 1.0);

        // Article: Channel R = 0-180°, Channel G = 180-360°
        vec2  shadowSample = texture(uFaceShadowTex, vUV).rg;
        float texShadowDir = (dotR < 0.0) ? shadowSample.g : shadowSample.r;

        // step: shadowed when light angle exceeds the SDF value at this UV
        float dotFStep  = step(0.0, dotF); // 0 when light is behind head
        float faceShadow = step(dotRAcosDir, texShadowDir) * dotFStep;

        celColor = mix(uShadowColor * albedo, celColor, faceShadow);
    }
#endif


    // ================================================================
    // STEP 4 — ANISOTROPIC HAIR (optional — #define FEATURE_ANISO_HAIR)
    // Article: "hair shines when it receives light, remove sides with fresnel"
    // ================================================================
#ifdef FEATURE_ANISO_HAIR
    {
        float NdotV       = clamp(dot(N, V), 0.0, 1.0);
        float hairFresnel = pow(1.0 - NdotV, uAnisoFresnelPow) * uAnisoFresnelIntensity;
        float hairMask    = texture(uHairMask, vUV).r;
        // Gate by NdotL so hair only shines when facing the light
        float hairHighlight = clamp(1.0 - hairFresnel, 0.0, 1.0)
                            * hairMask
                            * clamp(lDot, 0.0, 1.0);
        celColor += vec3(hairHighlight); // additive white highlight
    }
#endif


    // ================================================================
    // STEP 5 — METALLIC (optional — #define FEATURE_METALLIC)
    // Article: "dot(normal, normalize(viewDir + lightDir)) for UV,
    //  sample gradient texture, optionally distort with normal map"
    // ================================================================
#ifdef FEATURE_METALLIC
    {
        vec3  H          = normalize(V + L);
        float metallicU  = dot(N, H) * 0.5 + 0.5; // remap [-1,1] to [0,1]
        vec3  metalColor = texture(uMetallicGradient, vec2(metallicU, 0.5)).rgb;
        celColor = mix(celColor, metalColor * albedo, uMetallicBlend);
    }
#endif


    // ================================================================
    // STEP 6 — LIGHT COLOR MULTIPLY
    // Article: "multiply final result by color light and fog"
    // ================================================================
    celColor *= uLightColor;


    // ================================================================
    // STEP 7 — AMBIENT FILL (kept from your original shader — good practice)
    // ================================================================
    celColor += albedo * uAmbientColor;


    // ================================================================
    // STEP 8 — RIM / EDGE HIGHLIGHT
    // Article: "white outline around character, detected via post-process Sobel"
    // This fresnel is a shader-side stand-in until you wire up vrm_outline.frag.
    // Gate it to the lit side so it doesn't glow in shadow.
    // ================================================================
    float rimDot    = 1.0 - clamp(dot(N, V), 0.0, 1.0);
    float rimFactor = pow(rimDot, uRimPow) * uRimIntensity;
    rimFactor      *= step(0.0, lDot); // only on lit side
    celColor       += uRimColor * rimFactor;


    // ================================================================
    // STEP 9 — GRAN TURISMO TONEMAPPER
    // Article recommends this over Unity's Neutral/ACES for anime style.
    // Keeps saturation intact while preventing blown-out brights.
    // ================================================================
    celColor = granTurismoTonemap(celColor);

    // Linear -> Gamma (keep your existing conversion)
    celColor = pow(celColor, vec3(1.0 / 2.2));

    FragColor = vec4(celColor, texColor.a);
}

)GLSL";
